In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/Users/berrio/.conda/envs/mlzoomcamp/lib/python3.11/site-packages/numpy/__init__.py'>

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1,2,3,4,5,6,11,3])

In [9]:
a[2]

3

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  4,  5,  6, 11,  3])

In [12]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
n = np.array([
    [1, 2,3],
    [4, 5, 6], 
    [7, 8, 9]
])

In [17]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0]

array([1, 2, 3])

In [19]:
n[0][2]

3

In [20]:
n[0][2] = 20

In [21]:
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [22]:
n[:, 2]

array([20,  6,  9])

In [23]:
n[:, 1] = [8, 8, 8]

In [24]:
n

array([[ 1,  8, 20],
       [ 4,  8,  6],
       [ 7,  8,  9]])

In [29]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [30]:
# element wise operations
np.random.seed(2)
np.random.randn(5,2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.seed(2)
(100 * np.random.randn(5, 2))

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [33]:
np.random.randint(low=0, high=100, size=(5,2))

array([[39, 67],
       [ 4, 42],
       [51, 38],
       [33, 58],
       [67, 69]])

In [35]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
a + 1 # this is possible because numpy

array([1, 2, 3, 4, 5])

In [37]:
a * 2

array([0, 2, 4, 6, 8])

In [44]:
b = (10 + (a * 2)) ** 2
b

array([100, 144, 196, 256, 324])

In [42]:
a + b

array([100, 145, 198, 259, 328])

In [46]:
a / b + 10

array([10.        , 10.00694444, 10.01020408, 10.01171875, 10.01234568])

In [52]:
# comparison operations
a

a >= 2

array([False, False,  True,  True,  True])

In [53]:
a > b

array([False, False, False, False, False])

In [56]:
a[b > a]

array([0, 1, 2, 3, 4])

In [57]:
# Summarizing operations

a.min()

0

In [58]:
a.max()

4

In [59]:
a.sum()

10

In [60]:
a.mean()

2.0

In [61]:
a.std()

1.4142135623730951