In [2]:
import numpy as np

In [3]:
u = np.array([2,4,5,6])

In [5]:
u

array([2, 4, 5, 6])

In [7]:
v = np.array([1,0,0,2])

In [8]:
c = u + v

array([3, 4, 5, 8])

In [9]:
u *2

array([ 4,  8, 10, 12])

Vector - Vector Multiplication

In [11]:
u * v

array([ 2,  0,  0, 12])

In [14]:
z = np.dot(u, v)
z

14

In [20]:
def vect_vect_multi(a, b):
    assert a.shape[0] == v.shape[0]
    n = a.shape[0]
    result = 0
    for i in range(n):
        result = result + a[i] * b[i]
        
    return result

In [21]:
res = vect_vect_multi(u, v)

res

14

In [22]:
u.dot(v)

14

Matrix - Vector  Multiplication

In [26]:
u = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

v = np.array([1, 0.5, 2, 1])

In [27]:
def matrix_vector_multi(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vect_vect_multi(U[i], v)
        
    return result
        

In [28]:
res = matrix_vector_multi(u, v)
res

array([20. ,  6. ,  8.5])

In [32]:
u.dot(v)

array([20. ,  6. ,  8.5])

Matrix - Matrix multiplication

In [36]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [34]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [35]:
V.dot(U)

array([[ 9. ,  8. , 10. , 10. ],
       [ 3.5,  2. ,  2.5,  2. ],
       [ 5. ,  5. ,  4. ,  5. ],
       [ 5. , 10. , 11. , 14. ]])

In [39]:
def matrix_matrix_multi(U,V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    
    res = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multi(U, vi)
        res[:, i] = Uvi
        
    return res

In [40]:
matrix_matrix_multi(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix : I

In [41]:
u = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]

np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
ee = np.eye(3)
V.dot(ee)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Matrix Inverse

Only possible for square matrices

In [44]:
Vs =  V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [46]:
Vs_inv = np.linalg.inv(Vs)

In [47]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])